name: CI

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.3.7' # Specify the Ruby version you are using

    - name: Install dependencies
      run: |
        gem install bundler
        bundle install

    - name: Copy theme directory
      run: cp -r elementary /github/workspace/elementary

    - name: Build site
      run: bundle exec jekyll build

    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/develop'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site